version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    restart: always
    networks:
      - internal
    cap_add:
      - NET_ADMIN
    privileged: true
    dns:
      - 0.0.0.0

networks:
  internal:
    driver: bridge
